# Generated by Django 5.1.2 on 2025-01-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialty',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='availability',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
