# Generated by Django 5.1.2 on 2025-01-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_app', '0002_specialization_remove_doctorprofile_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
