# Generated by Django 5.2.17 on 2026-10-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_app', '0004_appointment_fee_appointment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Scheduled', max_length=20),
        ),
    ]
